confetti_amount:
  default: 100
  type: integer
  description: "The amount of confetti used on each click."

confetti_spread:
  default: 360
  type: integer
  description: "The spread of confetti around on each click. All values are in degrees."

allowed_in:
  default: ""
  type: string
  description: "Enter the category(s)' slugs, separated by '|'. To enable confetti in all categories, leave this blank."
