confetti_amount:
  default: 100
  type: integer

confetti_spread:
  default: 360
  type: integer

allowed_in_categories:
  default: general
  type: list
  list_type: category

allowed_in_urls:
  default: ""
  type: list
